export const ADMIN_FORGETPASSWORD_REQUEST =
    "ADMIN_FORGETPASSWORD_REQUEST";
export const ADMIN_FORGETPASSWORD_SUCCESS =
    "ADMIN_FORGETPASSWORD_SUCCESS";
export const ADMIN_FORGETPASSWORD_FAIL =
    "ADMIN_FORGETPASSWORD_FAIL";

export const ADMIN_RESETPASSWORD_REQUEST =
    "ADMIN_RESETPASSWORD_REQUEST";
export const ADMIN_RESETPASSWORD_SUCCESS =
    "ADMIN_RESETPASSWORD_SUCCESS";
export const ADMIN_RESETPASSWORD_FAIL =
    "ADMIN_RESETPASSWORD_FAIL";
