export const GET_TOTALCANDIDATES_REQUEST = "GET_TOTALCANDIDATES_REQUEST";
export const GET_TOTALCANDIDATES_SUCCESS = "GET_TOTALCANDIDATES_SUCCESS";
export const GET_TOTALCANDIDATES_FAIL = "GET_TOTALCANDIDATES_FAIL";

export const GET_CANDIDATESPASSED_REQUEST = "GET_TOTALCANDIDATESPASSED_REQUEST";
export const GET_CANDIDATESPASSED_SUCCESS = "GET_TOTALCANDIDATESPASSED_SUCCESS";
export const GET_CANDIDATESPASSED_FAIL = "GET_TOTALCANDIDATESPASSED_FAIL";

export const GET_CANDIDATESFAILED_REQUEST = "GET_CANDIDATESFAILED_REQUEST";
export const GET_CANDIDATESFAILED_SUCCESS = "GET_CANDIDATESFAILED_SUCCESS";
export const GET_CANDIDATESFAILED_FAIL = "GET_CANDIDATESFAILED_FAIL";

export const DELETE_EACHCANDIDATE_BYID_REQUEST =
  "DELETE_EACHCANDIDATE_BYID_REQUEST";
export const DELETE_EACHCANDIDATE_BYID_SUCCESS =
  "DELETE_EACHCANDIDATE_BYID_SUCCESS";
export const DELETE_EACHCANDIDATE_BYID_FAIL = "DELETE_EACHCANDIDATE_BYID_FAIL";
export const DELETE_EACHCANDIDATE_BYID_RESET =
  "DELETE_EACHCANDIDATE_BYID_RESET";
