export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAIL = "QUESTION_FAIL";

export const SCORE_REQUEST = "SCORE_REQUEST";
export const SCORE_SUCCESS = "SCORE_SUCCESS";
export const SCORE_FAIL = "SCORE_FAIL";
