export const QUESTIONS_REQUEST = "QUESTIONS_REQUEST";
export const QUESTIONS_SUCCESS = "QUESTIONS_SUCCESS";
export const QUESTIONS_FAIL = "QUESTIONS_FAIL";
export const QUESTIONS_RESET = "QUESTIONS_RESET";

export const TEST_REQUEST = "TEST_REQUEST";
export const TEST_SUCCESS = "TEST_SUCCESS";
export const TEST_FAIL = "TEST_FAIL";

export const QUESTION_FAIL = "QUESTION_FAIL";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_RESET = "QUESTION_RESET";

export const USER_GETALLQUESTIONS_REQUEST = "USER_GETALLQUESTIONS_REQUEST";
export const USER_GETALLQUESTIONS_SUCCESS = "USER_GETALLQUESTIONS_SUCCESS";
export const USER_GETALLQUESTIONS_FAIL = "USER_GETALLQUESTIONS_FAIL";

export const GET_QUESTION_BYID_REQUEST = "GET_QUESTION_BYID_REQUEST";
export const GET_QUESTION_BYID_SUCCESS = "GET_QUESTION_BYID_SUCCESS";
export const GET_QUESTION_BYID_FAIL = "GET_QUESTION_BYID_FAIL";

export const GET_EACHQUESTION_BYID_REQUEST = "GET_EACHQUESTION_BYID_REQUEST";
export const GET_EACHQUESTION_BYID_SUCCESS = "GET_EACHQUESTION_BYID_SUCCESS";
export const GET_EACHQUESTION_BYID_FAIL = "GET_EACHQUESTION_BYID_FAIL";

export const DELETE_CANDIDATE_BYID_REQUEST = "DELETE_CANDIDATE_BYID_REQUEST";
export const DELETE_CANDIDATE_BYID_SUCCESS = "DELETE_CANDIDATE_BYID_SUCCESS";
export const DELETE_CANDIDATE_BYID_FAIL = "DELETE_CANDIDATE_BYID_FAIL";

export const DELETE_QUESTION_BYID_REQUEST = "DELETE_QUESTION_BYID_REQUEST";
export const DELETE_QUESTION_BYID_SUCCESS = "DELETE_QUESTION_BYID_SUCCESS";
export const DELETE_QUESTION_BYID_FAIL = "DELETE_QUESTION_BYID_FAIL";
export const DELETE_QUESTION_BYID = "DELETE_QUESTION_BYID";
// export const DELETE_QUESTION_BYID_RESET = "DELETE_QUESTION_BYID_RESET";

export const EDITQUESTION_BYID_REQUEST = "EDITQUESTION_BYID_REQUEST";
export const EDITQUESTION_BYID_SUCCESS = "EDITQUESTION_BYID_SUCCESS";
export const EDITQUESTION_BYID_FAIL = "EDITQUESTION_BYID_FAIL";
