export const CREATE_SECTION_REQUEST = 'CREATE_SECTION_REQUEST'
export const CREATE_SECTION_SUCCESS = 'CREATE_SECTION_SUCCESS'
export const CREATE_SECTION_FAIL = 'CREATE_SECTION_FAIL'
export const CREATE_SECTION_RESET = 'CREATE_SECTION_RESET'

export const GET_SECTION_REQUEST = 'GET_SECTION_REQUEST'
export const GET_SECTION_SUCCESS = 'GET_SECTION_SUCCESS'
export const GET_SECTION_FAIL = 'GET_SECTION_FAIL'

export const DELETE_SECTION_REQUEST = 'DELETE_SECTION_REQUEST'
export const DELETE_SECTION_SUCCESS = 'DELETE_SECTION_SUCCESS'
export const DELETE_SECTION_FAIL = 'DELETE_SECTION_FAIL'
export const DELETE_SECTION_RESET = 'DELETE_SECTION_RESET'


export const GET_SECTION_BYID_REQUEST = 'GET_SECTION_BYID_REQUEST'
export const GET_SECTION_BYID_SUCCESS = 'GET_SECTION_BYID_SUCCESS'
export const GET_SECTION_BYID_FAIL = 'GET_SECTION_BYID_FAIL'