export const TESTSCORE_REQUEST = "TESTSCORE_REQUEST";
export const TESTSCORE_SUCCESS = "TESTSCORE_SUCCESS";
export const TESTSCORE_FAIL = "TESTSCORE_FAIL";

export const TEST_TIME_REQUEST = "TEST_TIME_REQUEST";
export const TEST_TIME_SUCCESS = "TEST_TIME_SUCCESS";
export const TEST_TIME_FAIL = "TEST_TIME_FAIL";