// export const CREATE_TEST_REQUEST = 'CREATE_TEST_REQUEST'
// export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS'
// export const CREATE_TEST_FAIL = 'CREATE_TEST_FAIL'
// export const CREATE_TEST_RESET = 'CREATE_TEST_RESET'

// export const GET_TEST_REQUEST = 'GET_TEST_REQUEST'
// export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS'
// export const GET_TEST_FAIL = 'GET_TEST_FAIL'

// export const DELETE_TEST_REQUEST = 'DELETE_TEST_REQUEST'
// export const DELETE_TEST_SUCCESS = 'DELETE_TEST_SUCCESS'
// export const DELETE_TEST_FAIL = 'DELETE_TEST_FAIL'
// export const DELETE_TEST_RESET = 'DELETE_TEST_RESET'