export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";
export const USER_REGISTRATION_RESET = "USER_REGISTRATION_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

/*ADMIN  */

export const USERS_REGISTRATION_REQUEST = "USERS_REGISTRATION_REQUEST";
export const USERS_REGISTRATION_SUCCESS = "USERS_REGISTRATION_SUCCESS";
export const USERS_REGISTRATION_FAIL = "USERS_REGISTRATION_FAIL";
export const USERS_REGISTRATION_RESET = "USERS_REGISTRATION_RESET";

export const USERS_LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const USERS_LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const USERS_LOGIN_FAIL = "USERS_LOGIN_FAIL";
export const USERS_LOGOUT = "USERS_LOGOUT";

export const USERS_DETAILS_REQUEST = "USERS_DETAILS_REQUEST";
export const USERS_DETAILS_SUCCESS = "USERS_DETAILS_SUCCESS";
export const USERS_DETAILS_FAIL = "USERS_DETAILS_FAIL";

export const USER_VIEWADMIN_REQUEST = "USER_VIEWADMIN_REQUEST";
export const USER_VIEWADMIN_SUCCESS = "USER_VIEWADMIN_SUCCESS";
export const USER_VIEWADMIN_FAIL = "USER_VIEWADMIN_FAIL";

export const USER_SECTION_REQUEST = "USER_SECTION_REQUEST";
export const USER_SECTION_SUCCESS = "USER_SECTION_SUCCESS";
export const USER_SECTION_FAIL = "USER_SECTION_FAIL";

export const GETALLADMIN_REQUEST = "GETALLADMIN_REQUEST";
export const GETALLADMIN_SUCCESS = "GETALLADMIN_SUCCESS";
export const GETALLADMIN_FAIL = "GETALLADMIN_FAIL";

export const GETCANDIDATESDETAILS_REQUEST = "GETCANDIDATESDETAILS_REQUEST";
export const GETCANDIDATESDETAILS_SUCCESS = "GETCANDIDATESDETAILS_SUCCESS";
export const GETCANDIDATESDETAILS_FAIL = "GETCANDIDATESDETAILS_FAIL";

export const GETALL_CANDIDATES_DETAILS_REQUEST =
  "GETALL_CANDIDATES_DETAILS_REQUEST";
export const GETALL_CANDIDATES_DETAILS_SUCCESS =
  "GETALL_CANDIDATES_DETAILS_SUCCESS";
export const GETALL_CANDIDATES_DETAILS_FAIL = "GETALL_CANDIDATES_DETAILS_FAIL";

export const DELETE_ADMIN_BYID_REQUEST = "DELETE_ADMIN_BYID_REQUEST";
export const DELETE_ADMIN_BYID_SUCCESS = "DELETE_ADMIN_BYID_SUCCESS";
export const DELETE_ADMIN_BYID_FAIL = "DELETE_ADMIN_BYID_FAIL";
