// export const USERS_REGISTRATION_REQUEST =
//     "USERS_REGISTRATION_REQUEST";
// export const USERS_REGISTRATION_SUCCESS =
//     "USERS_REGISTRATION_SUCCESS";
// export const USERS_REGISTRATION_FAIL =
//     "USERS_REGISTRATION_FAIL";
// export const USERS_REGISTRATION_RESET =
//     "USERS_REGISTRATION_RESET";

// export const USERS_LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
// export const USERS_LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
// export const USERS_LOGIN_FAIL = "USERS_LOGIN_FAIL";
// export const USERS_LOGOUT = "USERS_LOGOUT";

// export const USERS_DETAILS_REQUEST = "USERS_DETAILS_REQUEST";
// export const USERS_DETAILS_SUCCESS = "USERS_DETAILS_SUCCESS";
// export const USERS_DETAILS_FAIL = "USERS_DETAILS_FAIL";

// export const USER_VIEWADMIN_REQUEST =
//     "USER_VIEWADMIN_REQUEST";
// export const USER_VIEWADMIN_SUCCESS =
//     "USER_VIEWADMIN_SUCCESS";
// export const USER_VIEWADMIN_FAIL = "USER_VIEWADMIN_FAIL";

// export const USER_SECTION_REQUEST = "USER_SECTION_REQUEST";
// export const USER_SECTION_SUCCESS = "USER_SECTION_SUCCESS";
// export const USER_SECTION_FAIL = "USER_SECTION_FAIL";

// export const GETALLADMIN_REQUEST = "GETALLADMIN_REQUEST";
// export const GETALLADMIN_SUCCESS = "GETALLADMIN_SUCCESS";
// export const GETALLADMIN_FAIL = "GETALLADMIN_FAIL";

// export const GETCANDIDATESDETAILS_REQUEST =
//     "GETCANDIDATESDETAILS_REQUEST";
// export const GETCANDIDATESDETAILS_SUCCESS =
//     "GETCANDIDATESDETAILS_SUCCESS";
// export const GETCANDIDATESDETAILS_FAIL =
//     "GETCANDIDATESDETAILS_FAIL";
