export const USER_TOKEN_REQUEST = "USER_TOKEN_REQUEST";
export const USER_TOKEN_SUCCESS = "USER_TOKEN_SUCCESS";
export const USER_TOKEN_FAIL = "USER_TOKEN_FAIL";
export const USER_TOKEN_RESET = "USER_TOKEN_RESET";

export const CHECKIN_TOKEN_REQUEST = "CHECKIN_TOKEN_REQUEST";
export const CHECKIN_TOKEN_SUCCESS = "CHECKIN_TOKEN_SUCCESS";
export const CHECKIN_TOKEN_FAIL = "CHECKIN_TOKEN_FAIL";
export const CHECKIN_TOKEN_RESET = "CHECKIN_TOKEN_RESET";

export const CHECKOUT_TOKEN_REQUEST = "CHECKOUT_TOKEN_REQUEST";
export const CHECKOUT_TOKEN_SUCCESS = "CHECKOUT_TOKEN_SUCCESS";
export const CHECKOUT_TOKEN_FAIL = "CHECKOUT_TOKEN_FAIL";
export const CHECKOUT_TOKEN_RESET = "CHECKOUT_TOKEN_RESET";
