export { default as HomeScreen } from "./HomeScreen";
export { default as Dashboard } from "./Admin/Dashboard";
export { default as Confirmation } from "./Admin/Confirmation";
export { default as EditConfirmation } from "./Admin/Confirmation/Edit";
export { default as Roles } from "./Admin/Config/";
export { default as AdminReport } from "./Admin/Config/adminCompleted";
export { default as Role } from "./Admin/Config/Role";
export { default as Location } from "./Admin/Config/Location";
export { default as Division } from "./Admin/Config/Division";
export { default as Department } from "./Admin/Config/Department";
export { default as AdminPending } from "./Admin/Pending";
export { default as AdminViewPending } from "./Admin/Pending/View";
export { default as AdminViewRating } from "./Admin/Pending/Rating";
export { default as AdminCompleted } from "./Admin/Completed";
export { default as AdminCompletedView } from "./Admin/Completed/View";
export { default as AdminCompletedReport } from "./Admin/Completed/report";
export { default as AdminCompletedPerformance } from "./Admin/Completed/performance";
export { default as AdminCompletedBehavioural } from "./Admin/Completed/behavioural";
export { default as AdminCompletedDocumentation } from "./Admin/Completed/documentation";
export { default as AdminCompletedSupervisory } from "./Admin/Completed/supervisory";
export { default as AdminCompletedSummary } from "./Admin/Completed/summary";
export { default as AdminCompletedViewDetails } from "./ConfirmationForm/ViewRequestDetails/completedView";
export { default as RequestPage } from "./ConfirmationForm/RequestPage";
export { default as behavioral_Section1 } from "./ConfirmationForm/performanceFactor/Others/behaviouralTrait";
export { default as Rater_behavioral_Section1 } from "./ConfirmationForm/performanceFactor/Raters/behaviouralTrait";
// export { default as Section2 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 2";
export { default as Section3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3";
// export { default as Section1__Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 1";
export { default as Section2__Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 2";
export { default as PendingRequests } from "./ConfirmationForm/PendingRequests";
export { default as LineManagerPendingPage } from "./ConfirmationForm/PendingRequests/LineManagerPendingPage";
export { default as HrbpPendingPage } from "./ConfirmationForm/PendingRequests/HrbpPendingPage";
export { default as HrAdminstrationPendingPage } from "./ConfirmationForm/PendingRequests/HrAdminstrationPendingPage";
export { default as SeniorManagerESPendingPage } from "./ConfirmationForm/PendingRequests/SeniorManagerESPendingPage";
export { default as GmHrOperationsPendingPage } from "./ConfirmationForm/PendingRequests/GmHrOperationsPendingPage";
export { default as ChiefHROfficerPendingPage } from "./ConfirmationForm/PendingRequests/ChiefHROfficerPendingPage";
export { default as ViewRequestDetails } from "./ConfirmationForm/ViewRequestDetails";
export { default as Rater_WelcomePage } from "./ConfirmationForm/performanceFactor/Raters/welcomePage";
export { default as Rater_Performance_Section1 } from "./ConfirmationForm/performanceFactor/Raters/pageOne";
// export { default as Rater_Performance_Section2 } from "./ConfirmationForm/performanceFactor/Raters/pageTwo";
export { default as Performance_Section1 } from "./ConfirmationForm/performanceFactor/Others/pageOne";
export { default as Performance_Section2 } from "./ConfirmationForm/performanceFactor/Others/pageTwo";
export { default as Level3HSupervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 1/3HsupervisorySection1";
export { default as GetSuperVisorySection1 } from "./ConfirmationForm/Supervisory/Supervisory Section 1/GetSupervisorySection1";
export { default as GetBehavioralSection2Rating } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 2/GetBehavioralSection2Rating";
export { default as GetBehavioralSection3Rating } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/GetBehavioralSection3Rating";
export { default as LineManagerView } from "./ConfirmationForm/Supervisory/view-ratings/LineManager";
export { default as ReviewerView } from "./ConfirmationForm/Supervisory/view-ratings/Reviewer";
export { default as ConfirmationSummary } from "./ConfirmationForm/Supervisory/view-ratings/ConfirmationSummary";
export { default as SMESView } from "./ConfirmationForm/Supervisory/view-ratings/SnrMgrEmployee";
export { default as MHRBPView } from "./ConfirmationForm/Supervisory/view-ratings/MHRBP";
export { default as HRAdminView } from "./ConfirmationForm/Supervisory/view-ratings/HRAdmin";
export { default as Level3HHr } from "./ConfirmationForm/Supervisory/view-ratings/3HHrAdmin";
// export { default as ManagerIndustrialRelationshipView } from "./ConfirmationForm/Supervisory/view-ratings/ManagerIndRel";
// export { default as EmployeeView } from "./ConfirmationForm/Supervisory/view-ratings/Employee";
export { default as GMHRView } from "./ConfirmationForm/Supervisory/view-ratings/GMHr";

export { default as ViewSmeLevel3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/viewbehavioralLevel3/smeConfirmation";

export { default as Level3BelowSummary } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/viewbehavioralLevel3/ConfirmationSummary";
export { default as Level3HsummaryHr } from "./ConfirmationForm/Supervisory/view-ratings/ConfirmationSummary";
export { default as Level4summary } from "./ConfirmationForm/Supervisory/view-ratings/level4Summary";
export { default as Chrosummary } from "./ConfirmationForm/Supervisory/view-ratings/ChroSummary";
// export { default as RaterBehavioralTraitTwo } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/level3belowBehaviorail";
export { default as ViewLineMangerLevel3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/viewbehavioralLevel3/linemanger";
export { default as ViewHrbpLevel3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/viewbehavioralLevel3/hrbp";

export { default as ViewHrLevel3 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/viewbehavioralLevel3/hcmHr";
export { default as ChiefHROfficer } from "./ConfirmationForm/Supervisory/view-ratings/ChiefHROfficer";
export { default as ViewSection2 } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 2/GetbehavioralRole";
export { default as EditRaterSection1 } from "./ConfirmationForm/EditRaterComments/performanceFactor/EditRaterSection1";
export { default as EditRaterSection2 } from "./ConfirmationForm/EditRaterComments/performanceFactor/EditRaterSection2";
export { default as RejectedPendingRequest } from "./ConfirmationForm/PendingRequests/RejectPendingRequest";
export { default as EditBehavioral } from "./ConfirmationForm/EditRaterComments/BehavioralTrait/behaviouralTrait";
export { default as EditBehavioral2 } from "./ConfirmationForm/EditRaterComments/BehavioralTrait/GetBehavioralSection2Rating";
export { default as EditBehavioral3 } from "./ConfirmationForm/EditRaterComments/BehavioralTrait/GetBehavioralSection3Rating";
export { default as Level3EditBehavioral } from "./ConfirmationForm/EditRaterComments/BehavioralTrait/level3belowBehaviorail";
export { default as EditSupervisory1 } from "./ConfirmationForm/EditRaterComments/supervisory/supervisorySection1";
export { default as EditSupervisory2 } from "./ConfirmationForm/EditRaterComments/supervisory/supervisorySection2";
export { default as level3Supervisory } from "./ConfirmationForm/Supervisory/Supervisory Section 1/level3Supervisory";
export { default as level3ConfirmationSummary } from "./ConfirmationForm/Supervisory/view-ratings/Level3ConfirmationSummary";
export { default as level3Summary } from "./ConfirmationForm/Supervisory/view-ratings/level3summary";
export { default as level2HrCloseOut } from "./ConfirmationForm/Behavioural Traits Evaluation/Section 3/viewbehavioralLevel3/SmeCloseOut";
export { default as level3HrCloseOut } from "./ConfirmationForm/Supervisory/view-ratings/Level3closeout";
export { default as level3HHrCloseOut } from "./ConfirmationForm/Supervisory/view-ratings/Level3HCloseOut";
export { default as level4HrCloseOut } from "./ConfirmationForm/Supervisory/view-ratings/Level4Closeout";
export { default as HrCloseOutTable } from "./ConfirmationForm/PendingRequests/HrCloseOut";
export { default as HrViewTable } from "./ConfirmationForm/PendingRequests/HRView";
