export const EDIT_DEPARTMENTBYID_REQUEST = "EDIT_DEPARTMENTBYID_REQUEST";
export const EDIT_DEPARTMENTBYID_SUCCESS = "EDIT_DEPARTMENTBYID_SUCCESS";
export const EDIT_DEPARTMENTBYID_FAIL = "EDIT_DEPARTMENTBYID_FAIL";
export const EDIT_DEPARTMENTBYID_RESET = "EDIT_DEPARTMENTBYID_RESET";

export const GET_DEPARTMENTBYID_REQUEST = "GET_DEPARTMENTBYID_REQUEST";
export const GET_DEPARTMENTBYID_SUCCESS = "GET_DEPARTMENTBYID_SUCCESS";
export const GET_DEPARTMENTBYID_FAIL = "GET_FACULTYBYID_FAIL";

export const DELETE_DEPARTMENTBYID_REQUEST = "DELETE_DEPARTMENTBYID_REQUEST";
export const DELETE_DEPARTMENTBYID_SUCCESS = "DELETE_DEPARTMENTBYID_SUCCESS";
export const DELETE_DEPARTMENTBYID_FAIL = "DELETE_FACULTYBYID_FAIL";
export const DELETE_DEPARTMENTBYID_RESET = "DELETE_DEPARTMENTBYID_RESET";
