export const EDIT_STAFFBYID_REQUEST = "EDIT_STAFFBYID_REQUEST";
export const EDIT_STAFFBYID_SUCCESS = "EDIT_STAFFBYID_SUCCESS";
export const EDIT_STAFFBYID_FAIL = "EDIT_STAFFBYID_FAIL";
export const EDIT_STAFFBYID_RESET = "EDIT_STAFFBYID_RESET";

export const GET_STAFFBYID_REQUEST = "GET_STAFFBYID_REQUEST";
export const GET_STAFFBYID_SUCCESS = "GET_STAFFBYID_SUCCESS";
export const GET_STAFFBYID_FAIL = "GET_STAFFBYID_FAIL";

export const DELETE_STAFFBYID_REQUEST = "DELETE_STAFFBYID_REQUEST";
export const DELETE_STAFFBYID_SUCCESS = "DELETE_STAFFBYID_SUCCESS";
export const DELETE_STAFFBYID_FAIL = "DELETE_SAFFBYID_FAIL";
export const DELETE_STAFFBYID_RESET = "DELETE_STAFFBYID_RESET";
