export const EDIT_STUDENTBYID_REQUEST = "EDIT_STUDENTBYID_REQUEST";
export const EDIT_STUDENTBYID_SUCCESS = "EDIT_STUDENTBYID_SUCCESS";
export const EDIT_STUDENTBYID_FAIL = "EDIT_STUDENTBYID_FAIL";
export const EDIT_STUDENTBYID_RESET = "EDIT_STUDENTBYID_RESET";

export const GET_STUDENTBYID_REQUEST = "GET_STUDENTBYID_REQUEST";
export const GET_STUDENTBYID_SUCCESS = "GET_STUDENTBYID_SUCCESS";
export const GET_STUDENTBYID_FAIL = "GET_STUDENTBYID_FAIL";
// export const GET_STUDENTBYID_RESET = "GET_STUDENTBYID_RESET";
