export const EDIT_COURSEBYID_REQUEST = "EDIT_COURSEBYID_REQUEST";
export const EDIT_COURSEBYID_SUCCESS = "EDIT_COURSEBYID_SUCCESS";
export const EDIT_COURSEBYID_FAIL = "EDIT_COURSEBYID_FAIL";
export const EDIT_COURSEBYID_RESET = "EDIT_COURSEBYID_RESET";

export const GET_COURSEBYID_REQUEST = "GET_COURSEBYID_REQUEST";
export const GET_COURSEBYID_SUCCESS = "GET_COURSEBYID_SUCCESS";
export const GET_COURSEBYID_FAIL = "GET_COURSEBYID_FAIL";

export const DELETE_COURSEBYID_REQUEST = "DELETE_COURSEBYID_REQUEST";
export const DELETE_COURSEBYID_SUCCESS = "DELETE_COURSEBYID_SUCCESS";
export const DELETE_COURSEBYID_FAIL = "DELETE_COURSEBYID_FAIL";
export const DELETE_COURSEBYID_RESET = "DELETE_COURSEBYID_RESET";
