export const EDIT_FACULTYBYID_REQUEST = "EDIT_FACULTYBYID_REQUEST";
export const EDIT_FACULTYBYID_SUCCESS = "EDIT_FACULTYBYID_SUCCESS";
export const EDIT_FACULTYBYID_FAIL = "EDIT_FACULTYBYID_FAIL";
export const EDIT_FACULTYBYID_RESET = "EDIT_FACULTYBYID_RESET";

export const GET_FACULTYBYID_REQUEST = "GET_FACULTYBYID_REQUEST";
export const GET_FACULTYBYID_SUCCESS = "GET_FACULTYBYID_SUCCESS";
export const GET_FACULTYBYID_FAIL = "GET_FACULTYBYID_FAIL";

export const DELETE_FACULTYBYID_REQUEST = "DELETE_FACULTYBYID_REQUEST";
export const DELETE_FACULTYBYID_SUCCESS = "DELETE_FACULTYBYID_SUCCESS";
export const DELETE_FACULTYBYID_FAIL = "DELETE_FACULTYBYID_FAIL";
export const DELETE_FACULTYBYID_RESET = "DELETE_FACULTYBYID_RESET";
