export const DELETE_NOTICEBYID_REQUEST = "DELETE_NOTICEBYID_REQUEST";
export const DELETE_NOTICEBYID_SUCCESS = "DELETE_NOTICEBYID_SUCCESS";
export const DELETE_NOTICEBYID_FAIL = "DELETE_NOTICEBYID_FAIL";
export const DELETE_NOTICEBYID_RESET = "DELETE_NOTICEBYID_RESET";

export const EDIT_NOTICEBYID_REQUEST = "EDIT_NOTICEBYID_REQUEST";
export const EDIT_NOTICEBYID_SUCCESS = "EDIT_NOTICEBYID_SUCCESS";
export const EDIT_NOTICEBYID_FAIL = "EDIT_NOTICEBYID_FAIL";
export const EDIT_NOTICEBYID_RESET = "EDIT_NOTICEBYID_RESET";

export const GET_NOTICEBYID_REQUEST = "GET_NOTICEBYID_REQUEST";
export const GET_NOTICEBYID_SUCCESS = "GET_NOTICEBYID_SUCCESS";
export const GET_NOTICEBYID_FAIL = "GET_NOTICEBYID_FAIL";
