export const EDIT_USERPROFILE_REQUEST = "EDIT_USERPROFILE_REQUEST";
export const EDIT_USERPROFILE_SUCCESS = "EDIT_USERPROFILE_SUCCESS";
export const EDIT_USERPROFILE_FAIL = "EDIT_USERPROFILE_FAIL";
export const EDIT_USERPROFILE_RESET = "EDIT_USERPROFILE_RESET";
