export const CREATE_FACULTY_REQUEST = "CREATE_FACULTY_REQUEST";
export const CREATE_FACULTY_SUCCESS = "CREATE_FACULTY_SUCCESS";
export const CREATE_FACULTY_FAIL = "CREATE_FACULTY_FAIL";
export const CREATE_FACULTY_RESET = "CREATE_FACULTY_RESET";

export const GET_FACULTY_REQUEST = "GET_FACULTY_REQUEST";
export const GET_FACULTY_SUCCESS = "GET_FACULTY_SUCCESS";
export const GET_FACULTY_FAIL = "GET_FACULTY_FAIL";
