export const POST_INFORMATION_REQUEST = "POST_INFORMATION_REQUEST";
export const POST_INFORMATION_SUCCESS = "POST_INFORMATION_SUCCESS";
export const POST_INFORMATION_FAIL = "POST_INFORMATION_FAIL";
export const POST_INFORMATION_RESET = "POST_INFORMATION_RESET";

export const IMAGE_INFORMATION_REQUEST = "IMAGE_INFORMATION_REQUEST";
export const IMAGE_INFORMATION_SUCCESS = "IMAGE_INFORMATION_SUCCESS";
export const IMAGE_INFORMATION_FAIL = "IMAGE_INFORMATION_FAIL";
export const IMAGE_INFORMATION_RESET = "IMAGE_INFORMATION_RESET";

export const GET_INFORMATION_REQUEST = "GET_INFORMATION_REQUEST";
export const GET_INFORMATION_SUCCESS = "GET_INFORMATION_SUCCESS";
export const GET_INFORMATION_FAIL = "GET_INFORMATION_FAIL";
