export const GET_NOTICE_REQUEST = "GET_NOTICE_REQUEST";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
export const GET_NOTICE_FAIL = "GET_NOTICE_FAIL";

export const POST_NOTICE_REQUEST = "POST_NOTICE_REQUEST";
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAIL = "POST_NOTICE_FAIL";
export const POST_NOTICE_RESET = "POST_NOTICE_RESET";
