export const PROFILE_PICTURE_REQUEST = "PROFILE_PICTURE_REQUEST";
export const PROFILE_PICTURE_SUCCESS = "PROFILE_PICTURE_SUCCESS";
export const PROFILE_PICTURE_FAIL = "PROFILE_PICTURE_FAIL";
export const PROFILE_PICTURE_RESET = "PROFILE_PICTURE_RESET";
