export const GET_SCOPE_REQUEST = "GET_SCOPE_REQUEST";
export const GET_SCOPE_SUCCESS = "GET_SCOPE_SUCCESS";
export const GET_SCOPE_FAIL = "GET_SCOPE_FAIL";

export const POST_SCOPE_REQUEST = "POST_SCOPE_REQUEST";
export const POST_SCOPE_SUCCESS = "POST_SCOPE_SUCCESS";
export const POST_SCOPE_FAIL = "POST_SCOPE_FAIL";
export const POST_SCOPE_RESET = "POST_SCOPE_RESET";
