export const NEWSTAFF_REQUEST = "NEWSTAFF_REQUEST";
export const NEWSTAFF_SUCCESS = "NEWSTAFF_SUCCESS";
export const NEWSTAFF_FAIL = "NEWSTAFF_FAIL";
export const NEWSTAFF_RESET = "NEWSTAFF_RESET";

export const DELETE_STAFFBYID_REQUEST = "DELETE_STAFFBYID_REQUEST";
export const DELETE_STAFFBYID_SUCCESS = "DELETE_STAFFBYID_SUCCESS";
export const DELETE_STAFFBYID_FAIL = "DELETE_STAFFBYID_FAIL";

export const TOTAL_STAFF_REQUEST = "TOTAL_STAFF_REQUEST";
export const TOTAL_STAFF_SUCCESS = "TOTAL_STAFF_SUCCESS";
export const TOTAL_STAFF_FAIL = "TOTAL_STAFF_FAIL";
