export const GET_STUDENTGENERAL_DETAILS_REQUEST =
  "GET_STUDENTGENERAL_DETAILS_REQUEST";
export const GET_STUDENTGENERAL_DETAILS_SUCCESS =
  "GET_STUDENTGENERAL_DETAILS_SUCCESS";
export const GET_STUDENTGENERAL_DETAILS_FAIL =
  "GET_STUDENTGENERAL_DETAILS_FAIL";
