export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL";
export const CREATE_STUDENT_RESET = "CREATE_STUDENT_RESET";

export const TOTAL_STUDENT_REQUEST = "TOTAL_STUDENT_REQUEST";
export const TOTAL_STUDENT_SUCCESS = "TOTAL_STUDENT_SUCCESS";
export const TOTAL_STUDENT_FAIL = "TOTAL_STUDENT_FAIL";

export const DELETE_STUDENTBYID_REQUEST = "DELETE_STUDENTBYID_REQUEST";
export const DELETE_STUDENTBYID_SUCCESS = "DELETE_STUDENTBYID_SUCCESS";
export const DELETE_STUDENTBYID_FAIL = "DELETE_STUDENTBYID_FAIL";
export const DELETE_STUDENTBYID_RESET = "DELETE_STUDENTBYID_RESET";
