export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_FORGOTPASSWORD_REQUEST = "USER_FORGOTPASSWORD_REQUEST";
export const USER_FORGOTPASSWORD_SUCCESS = "USER_FORGOTPASSWORD_SUCCESS";
export const USER_FORGOTPASSWORD_FAIL = "USER_FORGOTPASSWORD_FAIL";
export const USER_FORGOTPASSWORD_RESET = "USER_FORGOTPASSWORD_RESET";

export const CONFIRMPASSWORD_REQUEST = "CONFIRMPASSWORD_REQUEST";
export const CONFIRMPASSWORD_SUCCESS = "CONFIRMPASSWORD_SUCCESS";
export const CONFIRMPASSWORD_FAIL = "CONFIRMPASSWORD_FAIL";
export const CONFIRMPASSWORD_RESET = "CONFIRMPASSWORD_RESET";
