export const USERS_DATA_REQUEST = "USERS_DATA_REQUEST";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";
export const USERS_DATA_FAIL = "USERS_DATA_FAIL";
export const USERS_DATA_RESET = "USERS_DATA_RESET";

export const CREATE_SPECIALIZATION_REQUEST = "CREATE_SPECIALIZATION_REQUEST";
export const CREATE_SPECIALIZATION_SUCCESS = "CREATE_SPECIALIZATION_SUCCESS";
export const CREATE_SPECIALIZATION_FAIL = "CREATE_SPECIALIZATION_FAIL";
export const CREATE_SPECIALIZATION_RESET = "CREATE_SPECIALIZATION_RESET";

export const GET_SPECIALIZATION_REQUEST = "GET_SPECIALIZATION_REQUEST";
export const GET_SPECIALIZATION_SUCCESS = "GET_SPECIALIZATION_SUCCESS";
export const GET_SPECIALIZATION_FAIL = "GET_SPECIALIZATION_FAIL";

export const ACADEMIC_DATA_REQUEST = "ACADEMIC_DATA_REQUEST";
export const ACADEMIC_DATA_SUCCESS = "ACADEMIC_DATA_SUCCESS";
export const ACADEMIC_DATA_FAIL = "ACADEMIC_DATA_FAIL";
export const ACADEMIC_DATA_RESET = "ACADEMIC_DATA_RESET";

export const HEALTH_DATA_REQUEST = "HEALTH_DATA_REQUEST";
export const HEALTH_DATA_SUCCESS = "ACADEMIC_DATA_SUCCESS";
export const HEALTH_DATA_FAIL = "HEALTH_DATA_FAIL";
export const HEALTH_DATA_RESET = "HEALTH_DATA_RESET";

export const FAMILY_DATA_REQUEST = "FAMILY_DATA_REQUEST";
export const FAMILY_DATA_SUCCESS = "FAMILY_DATA_SUCCESS";
export const FAMILY_DATA_FAIL = "FAMILY_DATA_FAIL";
export const FAMILY_DATA_RESET = "FAMILY_DATA_RESET";
