export const ADMIN_REGISTRATION_REQUEST = "ADMIN_REGISTRATION_REQUEST";
export const ADMIN_REGISTRATION_SUCCESS = "ADMIN_REGISTRATION_SUCCESS";
export const ADMIN_REGISTRATION_FAIL = "ADMIN_REGISTRATION_FAIL";
export const ADMIN_REGISTRATION_RESET = "ADMIN_REGISTRATION_RESET";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_RESET = "ADMIN_LOGIN_RESET";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";

export const ADMIN_FORGET_PASSWORD_REQUEST = "ADMIN_FORGET_PASSWORD_REQUEST";
export const ADMIN_FORGET_PASSWORD_SUCCESS = "ADMIN_FORGET_PASSWORD_SUCCESS";
export const ADMIN_FORGET_PASSWORD_FAIL = "ADMIN_FORGET_PASSWORD_FAIL";

export const ADMIN_CHANGE_PASSWORD_REQUEST = "ADMIN_CHANGE_PASSWORD_REQUEST";
export const ADMIN_CHANGE_PASSWORD_SUCCESS = "ADMIN_CHANGE_PASSWORD_SUCCESS";
export const ADMIN_CHANGE_PASSWORD_FAIL = "ADMIN_CHANGE_PASSWORD_FAIL";