export const PRE_BOOK_GUEST = "PRE_BOOK_GUEST";
export const PRE_BOOK_GUEST_FAIL = "PRE_BOOK_GUEST_FAIL";
export const PRE_BOOK_GUEST_SUCCESS = "PRE_BOOK_GUEST_SUCCESS";
export const PRE_BOOK_GUEST_RESET = "PRE_BOOK_GUEST_RESET";
export const GET_DASHBOARD = "GET_DASHBOARD";
export const GET_DASHBOARD_FAIL = "GET_DASHBOARD_FAIL";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
